services:
  primes:
    build:
      context: .
    image: ${REGISTRY}/primes:${VERSION}
    volumes:
      - ${PRIMES_FILE:-./input.txt}:${PRIMES_FILE:-/data/input.txt}:delegated
    ports:
      - 80:80
    command:
      - -serve
      - "80"
